name: Linux Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:   
      - name: Check installed dependencies
        run: |
          echo "Hello World"
      
      - name: Check installed dependencies
        run: |
          echo "Hello World"
  
      - name: Check installed dependencies
        run: |
          echo "Hello World"
      
      - name: Check installed dependencies
        run: |
          echo "Hello World"
      
      - name: Check installed dependencies
        run: |
          echo "Hello World"
  
      - name: Check installed dependencies
        run: |
          echo "Hello World"
